const mongoose = require("mongoose");
const Schema = mongoose.Schema;
let costCalculatorSchema = new Schema(
    {
        costFactorReel: {
            minCostPer1kFollowersForReel: Number,
            maxCostper1KFollowersForReel: Number,
            minCostPerLikeForReel: Number,
            maxCostperLikeForReel: Number,
            minCostPerCommentForReel: Number,
            maxCostperCommentForReel: Number,
            minTotalCost: Number,
            maxTotalCost: Number,
            influencerExactminTotalCost: Number,
            influencerExactmaxTotalCost: Number,
        },
        costFactorPosts: {
            minCostPer1kFollowersForPosts: Number,
            maxCostper1KFollowersForPosts: Number,
            minCostPerLikeForPosts: Number,
            maxCostperLikeForPosts: Number,
            minCostPerCommentForPosts: Number,
            maxCostperCommentForPosts: Number,
            minTotalCost: Number,
            maxTotalCost: Number,
            influencerExactminTotalCost: Number,
            influencerExactmaxTotalCost: Number,
        },
        costFactorStories: {
            minCostPer1kFollowersForStory: Number,
            maxCostper1KFollowersForStory: Number,
            minCostPerLikeForStory: Number,
            maxCostperLikeForStory: Number,
            minCostPerCommentForStory: Number,
            maxCostperCommentForStory: Number,
            minTotalCost: Number,
            maxTotalCost: Number,
            influencerExactminTotalCost: Number,
            influencerExactmaxTotalCost: Number,
        },
        costFactorIgtv: {
            minCostPer1kFollowersForIgtv: Number,
            maxCostper1KFollowersForIgtv: Number,
            minCostPerLikeForIgtv: Number,
            maxCostperLikeForIgtv: Number,
            minCostPerCommentForIgtv: Number,
            maxCostperCommentForIgtv: Number,
            minTotalCost: Number,
            maxTotalCost: Number,
            influencerExactminTotalCost: Number,
            influencerExactmaxTotalCost: Number,
        },
        costFactorSwipeUp: {
            minCostPer1kFollowersForSwipeUpStory: Number,
            maxCostper1KFollowersForSwipeUpStory: Number,
            minCostPerLikeForSwipeUpStory: Number,
            maxCostperLikeForSwipeUpStory: Number,
            minCostPerCommentForSwipeUpStory: Number,
            maxCostperCommentForSwipeUpStory: Number,
            minTotalCost: Number,
            maxTotalCost: Number,
            influencerExactminTotalCost: Number,
            influencerExactmaxTotalCost: Number,
        },
        costFactorVideo: {
            minCostPer1kFollowersForVideo: Number,
            maxCostper1KFollowersForVideo: Number,
            minCostPerLikeForVideo: Number,
            maxCostperLikeForVideo: Number,
            minCostPerCommentForVideo: Number,
            maxCostperCommentForVideo: Number,
            minTotalCost: Number,
            maxTotalCost: Number,
            influencerExactminTotalCost: Number,
            influencerExactmaxTotalCost: Number,
        },
    },
    {
        timestamps: true,
        collection: "BasicCost",
    }
);
module.exports = mongoose.model("BasicCost", costCalculatorSchema);