const mongoose = require("mongoose");
const Schema = mongoose.Schema;
let calculatorSchema = new Schema(
    {
        reel: {
            nanoFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            microFolowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            midTierFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            macroFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            megaFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            }
        },

        post: {
            nanoFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            microFolowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            midTierFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            macroFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            megaFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            }
        },

        story: {
            nanoFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            microFolowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            midTierFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            macroFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            megaFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            }
        },

        swipeupStory: {
            nanoFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            microFolowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            midTierFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            macroFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            megaFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            }
        },

        igtv: {
            nanoFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            microFolowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            midTierFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            macroFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            megaFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            }
        },

        video: {
            nanoFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            microFolowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            midTierFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            macroFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            },
            megaFollowers: {
                minFollowersRange: Number,
                maxFollowersRange: Number,
                budgetperFollowersRange: Number,
                creatorsCount: Number,
                multipleForBudgetReach: Number,
                multipleForBudgetLikesComment: Number,
                reach: Number,
                LikesComment: Number,
            }
        }

    },
    {
        timestamps: true,
        collection: "CalculatedCost",
    }
);
module.exports = mongoose.model("CalculatedCost", calculatorSchema);